<a href="https://colab.research.google.com/github/jpospina88/pytorch-deep-learning/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [5]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(size=(7, 7))
random_tensor, random_tensor.dtype

(tensor([[0.7603, 0.6851, 0.5587, 0.4723, 0.5866, 0.9622, 0.7157],
         [0.1971, 0.3484, 0.6570, 0.0307, 0.0816, 0.4250, 0.4033],
         [0.0389, 0.6252, 0.2240, 0.3391, 0.7330, 0.2815, 0.5597],
         [0.2675, 0.6079, 0.2503, 0.6050, 0.8722, 0.6317, 0.1591],
         [0.1019, 0.6183, 0.1087, 0.9278, 0.4930, 0.2190, 0.2036],
         [0.4514, 0.6288, 0.8761, 0.4647, 0.8940, 0.0717, 0.6862],
         [0.6996, 0.6544, 0.8499, 0.8197, 0.3329, 0.2091, 0.4909]]),
 torch.float32)

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [9]:
# Create another random tensor
random_tensor_2 = torch.rand(size=(1, 7))

# Perform matrix multiplication

# This is tensor multiplication, not matrix multiplication
# print(random_tensor, "*", random_tensor_2)
# print("Equals:", random_tensor * random_tensor_2)

# This is matrix multiplication (inner dimensions must match, so the second tensor is transposed with .T)
torch.matmul(random_tensor, random_tensor_2.T)

tensor([[1.4738],
        [0.6627],
        [0.9580],
        [0.8026],
        [0.5416],
        [1.4212],
        [1.1122]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [10]:
import random

# Set manual seed
RANDOM_SEED=0
torch.manual_seed(seed=RANDOM_SEED)

# Create two random tensors
random_tensor = torch.rand(size=(7, 7))
random_tensor_2 = torch.rand(size=(1, 7))

# Matrix multiply tensors
torch.matmul(random_tensor, random_tensor_2.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [23]:
torch.cuda.is_available()

device = "cuda" if torch.cuda.is_available() else "cpu"
device

# Set random seed on the GPU
RANDOM_SEED=0
torch.manual_seed(seed=RANDOM_SEED)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [21]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
torch.cuda.is_available()

# Create two random tensors on GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
device

tensor_1 = torch.rand(size=(2, 3))
tensor_1_gpu = tensor_1.to(device)
print(tensor_1_gpu, tensor_1_gpu.device)

tensor_2 = torch.rand(size=(2, 3))
tensor_2_gpu = tensor_2.to(device)
print(tensor_2_gpu, tensor_2_gpu.device)


tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') cuda:0
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0') cuda:0



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [25]:
# Perform matmul on tensor_A and tensor_B
tensor_matmul = torch.matmul(tensor_1_gpu, tensor_2_gpu.T)
tensor_matmul

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [27]:
# Find max
print(f"Maximum: {tensor_matmul.max()}")

# Find min
print(f"Minimum: {tensor_matmul.min()}")

Maximum: 0.5617256760597229
Minimum: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [28]:
# Find arg max
print(f"Index where max value occurs: {tensor_matmul.argmax()}")

# Find arg min
print(f"Index where min value occurs: {tensor_matmul.argmin()}")

Index where max value occurs: 3
Index where min value occurs: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed


# Create random tensor


# Remove single dimensions


# Print out tensors and their shapes
